# EXP003: ResNet50 + MSF + CBAM
name: "EXP003_CBAM"
backbone: "resnet50"
pretrained: true

feature_module: "multiscale"
attention: "cbam"
domain_generalization: "identity"

head: "softmax"
num_classes: 4
dropout: 0.5
